### ISSUE TITLE
可以考虑用criterion做性能评测

### ISSUE THREAD

**Issue by gcxfd** [leizongmin/simpledb#17]
参考 https://bheisler.github.io/criterion.rs/book/getting_started.html

可以生成这种性能报告
https://bheisler.github.io/criterion.rs/book/user_guide/html_report/Fibonacci2/Iterative/20/report/index.html

**Comment by gcxfd** [comment]
see https://github.com/leizongmin/simpledb/pull/18

**Comment by leizongmin** [comment]
已经合并。感谢
